# Generated by Django 4.0.5 on 2022-06-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltax_frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='songs',
            field=models.ManyToManyField(blank=True, null=True, related_name='artist', to='deltax_frontend.songs'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='artists',
            field=models.ManyToManyField(blank=True, null=True, related_name='Songs', to='deltax_frontend.artists'),
        ),
    ]
