# Generated by Django 4.0.5 on 2022-06-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deltax_frontend', '0002_artists_songs_alter_songs_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='Songs', to='deltax_frontend.songs'),
        ),
    ]
