# Generated by Django 4.0.5 on 2022-06-04 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deltax_frontend', '0003_alter_artists_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artists',
            name='songs',
        ),
        migrations.AddField(
            model_name='artists',
            name='songs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='deltax_frontend.songs'),
        ),
    ]
