# Generated by Django 4.0.5 on 2022-06-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deltax_frontend', '0004_remove_artists_songs_artists_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artists',
            name='songs',
        ),
    ]
